logging:
  level:
    root: warn
app:
  upload:
    minio:
      endpoint: http://192.168.5.219:9000
      key: admin
      secret: nancal.123
      region:
  product-line:
    code: myoql

  mybatis:
    package: db.mapper
  mongo:
    yapi:
      ds:
        uri: mongodb://dev:123@mongo:27017/yapi
      tables:
        - group
        - project
        - interface
        - interface_cat

spring:
  application:
    name: admin-api
  profiles:
    active: yuxh
  data:
    mongodb:
      uri: mongodb://dev:123@mongo:27017/lowcode

  datasource:
    username: dev
    password: 123
    url: jdbc:mysql://mariadb:3306/lowcode?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20


    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    client-name:
server:
  port: 8084