logging:
  level:
    root: warn

spring:
  application:
    name: admin-api
  profiles:
    active: yuxh
  data:
    mongodb:
      uri: mongodb://dev:123@mongo:27017/lowcode

  datasource:
    username: dev
    password: 123
    url: jdbc:mysql://mariadb:3306/lowcode?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      jdbc-url:


    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    client-name:
server:
  port: 8084