package nbcp.myoql.db.mongo.enums

/**
 * https://docs.mongodb.com/manual/reference/operator/query/
 */
enum class QueryProjectionEnum {
    eq,
    gt,
    gte,
    `in`,
    lt,
    lte,
    ne,
    nin,
    //--------------------
    and,
    not,
    nor,
    or,
    //---------------------
    exists,
    type,
    //---------------------
    expr,
    jsonSchema,
    mod,
    regex,
    text,
    where,
    //---------------------
    geoIntersects,
    geoWithin,
    near,
    nearSphere,
    box,
    center,
    centerSphere,
    geometry,
    maxDistance,
    minDistance,
    polygon,
    uniqueDocs,
    //---------------------
    all,
    elemMatch,
    size,
    //---------------------
    bitsAllClear,
    bitsAllSet,
    bitsAnyClear,
    bitsAnySet,
    //---------------------
    comment,
    //---------------------
    `$`,
    meta,
    slice
    //---------------------
    //---------------------

}