version: "3"
services:

  redis:
    image: redis
    container_name: redis_app
    ports:
      - 7379:6379
    restart: always
    command: redis-server --requirepass "1@#4"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    container_name: mongo_app
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yxh123
    volumes:
      - mongo_data:/data mongo